### PR TITLE
[Sender] Send out of process and async

### PR DESCRIPTION
**Pull request by segiddins**
\c @orta @kylef

### CODE REVIEW

**Comment by kylef** [comment]
Interesting, what happens if CocoaPods quits before curl has finished? (I'm not too sure how children processes are handled here)

**Comment by segiddins** [comment]
@kylef just verified that it still runs

**Comment by orta** [comment]
This works for me :+1:

**Comment by orta** [comment]
Any idea what's up with travis? Seems to be a while.

**Comment by segiddins** [comment]
Timing out after all the tests have run. Merging.

**Comment by floere** [comment]
:+1:

**Comment by hfossli** [comment]
Awesome

**Pull request merged**
