### PR TITLE
[Plugin] Fix pod try detection

### PR DESCRIPTION
**Pull request by segiddins**
\c @orta

### CODE REVIEW

**Comment by orta** [comment]
I don't have enough context to really understand if this is gonna fix it, but if it is, awesome :dancers: 

The fails are rubocop.

**Comment by segiddins** [comment]
The realpath is what fixes it `var` to `private/var`

**Comment by orta** [comment]
Cool, looks mergable on the RuboCop fix :+1:

**Comment by segiddins** [comment]
@orta feel free to do that, ✈️ later.

**Comment by orta** [comment]
:+1:

**Comment by segiddins** [comment]
<3 thanks Orta!

**Pull request merged**
